force-app/main/default/objects/User_Permissions_Snapshot__c/User_Permissions_Snapshot__c.object-meta.xml
<CustomObject>
    <label>User Permissions Snapshot</label>
    <nameField>
        <label>User Permissions Snapshot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Permissions Snapshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Permissions_Snapshot__c/fields/System_Permissions__c.field-meta.xml
<CustomField>
    <fullName>System_Permissions__c</fullName>
    <label>System Permissions</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Modify All Data</fullName>
            </value>
            <value>
                <fullName>Show App Launcher in Communities</fullName>
            </value>
            <value>
                <fullName>Manage Public Classic Email Templates</fullName>
            </value>
            <value>
                <fullName>Run Reports</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/initPermissionSnapshots.cls
public class initPermissionSnapshots implements Queueable {

	// init constructor params
	Map<Map<String, String>, List<Map<String, String>>> nameToPermissionMap = new Map<Map<String, String>, List<Map<String, String>>>();

	public initPermissionSnapshots(Map<Map<String, String>, List<Map<String, String>>> nameToPermissionMap){

		this.nameToPermissionMap = nameToPermissionMap;

	}

	public void execute(QueueableContext context) {
    
    	// to update System_Permissions__c, return new User Permission Snapshots    
        Map<Id, User_Permissions_Snapshot__c> newSnapshots = initAuditUtility.newSnapshotPermissions(nameToPermissionMap);

        // init batch container
		Map<Id, User_Permissions_Snapshot__c> batchedSnapshots = new Map<Id, User_Permissions_Snapshot__c>();
		
        if(!Test.isRunningTest()){ 	        

			// queue batch update
	        System.enqueueJob(new getSnapshotSystemPermissions(batchedSnapshots, newSnapshots));

	    }else{

	    	System.debug('testing');

	    }

	}
}